### ISSUE TITLE
Access denied for user 'root'@'172.16.26.3' (using password: YES)

### ISSUE THREAD

**Issue by deeztek** [MasaCMS/MasaCMS#111]
Trying to get Masa CMS working on Docker but getting the following error in container logs:

`2022-08-03T12:51:22.758827Z 200 [Note] Access denied for user 'root'@'172.16.26.3' (using password: YES)`

Using the the same root password on both the app and the the mysql containers still throws this error. It looks like something is missing from the documentation or I am missing something?

Thanks

**Comment by guustnieuwenhuis** [comment]
Are you using the docker-compose file from the Masa CMS repository? (/core/docker)

**Comment by deeztek** [comment]
Yes, I'm.

**Comment by guustnieuwenhuis** [comment]
Hi @deeztek,
Have you been able to fix the issue? We've been working with these setups without any issue.
