### ISSUE TITLE
Issue with Creating Form

### ISSUE THREAD

**Issue by melissa-serrano** [MasaCMS/MasaCMS#114]
When I try to create a form, it doesn't work. See below for script error description. I clicked on the text field button.

jquery.min.js?coreversion=7.3.7:2 Uncaught Error: Syntax error, unrecognized expression

**Comment by sejourla** [comment]
What version of Masa are you using? Also, can post the entire error, as well as a few details (i.e. how big the form is, a screenshot of the form)? There should also be something in the network response tab after you submit it.

Also, if it is a complex form, maybe try creating a simple one-field form to see if that works.

**Comment by melissa-serrano** [comment]
I am currently using 7.3.7. I noticed this issue since 7.3.6. Below is the error: 

Uncaught Error: Syntax error, unrecognized expression: &lt;li&gt;&#xd;&#xa;&#x9;&#x9;&#x9;&lt;ul class&#x3d;&quot;mura-tb-nav-utility&quot;&gt;&#xd;&#xa;&#x9;&#x9;&#x9;&#x9;&lt;li&gt;&lt;div id&#x3d;&quot;button-trash&quot; title&#x3d;&quot;Delete&quot;&gt;&lt;&#x2f;div&gt;&lt;&#x2f;li&gt;&#xd;&#xa;&#x9;&#x9;&#x9;&lt;&#x2f;ul&gt;&#xd;&#xa;&#x9;&#x9;&#x9;&lt;div class&#x3d;&quot;mura-tb-block&quot;&gt;&#xd;&#xa;&#x9;&#x9;&#x9;&#x9;&lt;span&gt;&lt;&#x2f;span&gt;&#xd;&#xa;&#x9;&#x9;&#x9;&lt;&#x2f;div&gt;&#xd;&#xa;&#x9;&#x9;&lt;&#x2f;li&gt;
    at se.error (jquery.min.js?coreversion=7.3.7:2:12975)
    at se.tokenize (jquery.min.js?coreversion=7.3.7:2:20957)
    at se.select (jquery.min.js?coreversion=7.3.7:2:21783)
    at Function.se [as find] (jquery.min.js?coreversion=7.3.7:2:6877)
    at w.fn.init.find (jquery.min.js?coreversion=7.3.7:2:24344)
    at new w.fn.init (jquery.min.js?coreversion=7.3.7:2:24833)
    at w (jquery.min.js?coreversion=7.3.7:2:950)
    at doRenderFieldBlock (jquery.templatebuilder.0.7.js:256:22)
    at doAddField (jquery.templatebuilder.0.7.js:249:5)
    at doCreateField (jquery.templatebuilder.0.7.js:240:4)
se.error @ jquery.min.js?coreversion=7.3.7:2
se.tokenize @ jquery.min.js?coreversion=7.3.7:2
se.select @ jquery.min.js?coreversion=7.3.7:2
se @ jquery.min.js?coreversion=7.3.7:2
find @ jquery.min.js?coreversion=7.3.7:2
w.fn.init @ jquery.min.js?coreversion=7.3.7:2
w @ jquery.min.js?coreversion=7.3.7:2
doRenderFieldBlock @ jquery.templatebuilder.0.7.js:256
doAddField @ jquery.templatebuilder.0.7.js:249
doCreateField @ jquery.templatebuilder.0.7.js:240
success @ jquery.templatebuilder.0.7.js:1258
c @ jquery.min.js?coreversion=7.3.7:2
fireWith @ jquery.min.js?coreversion=7.3.7:2
S @ jquery.min.js?coreversion=7.3.7:2
(anonymous) @ jquery.min.js?coreversion=7.3.7:2
load (async)
send @ jquery.min.js?coreversion=7.3.7:2
ajax @ jquery.min.js?coreversion=7.3.7:2
goLoadField @ jquery.templatebuilder.0.7.js:1252
(anonymous) @ jquery.templatebuilder.0.7.js:285
dispatch @ jquery.min.js?coreversion=7.3.7:2
v.handle @ jquery.min.js?coreversion=7.3.7:2
![Screenshot 2022-08-12 112734](https://user-images.githubusercontent.com/89926774/184389905-6ee8096d-5a2c-4084-8e6a-bd99868ce4e0.jpg)

**Comment by chexy** [comment]
Hello All,
I did some troubleshooting and it looks like the issue started with the 7.3.6 patch.  
It looks like the esapiencode method is not playing nice with the form editor.

Rolling back this change will get things working again but I am not sure if it opens up an security issues.

[Link to the release](https://github.com/MasaCMS/MasaCMS/commit/0a1bfa4ec0a24204a9a07459b3ca5f011014f712#diff-c335760a62dc71732e5ed52f59fde13b7923630f1137718be81904d12980a494)

The file: admin/core/views/cform/html.cfm
The change
```
-- <cfoutput>#rc.return#</cfoutput><cfabort>
++ <cfoutput>#esapiencode('html',rc.return)#</cfoutput><cfabort>
```

**Comment by guustnieuwenhuis** [comment]
This seems to be related to https://github.com/MasaCMS/MasaCMS/issues/116, we'll look into this.

**Comment by guustnieuwenhuis** [comment]
Since #166 is resolved, I'm also assuming this issue is fixed. Therefor I'm closing the ticket, if my assumption is incorrect, please reopen the ticket.
