### ISSUE TITLE
File Browser error - 404

### ISSUE THREAD

**Issue by guustnieuwenhuis** [MasaCMS/MasaCMS#118]
### Discussed in https://github.com/MasaCMS/MasaCMS/discussions/100

<div type='discussions-op-text'>

<sup>Originally posted by **tbugler70** June 25, 2022</sup>
Clean install of Masa (7.3.4) and the file browser wont load returning a 404 error on GET http://lvc.localhost/index.cfm/_api/json/v1/lvc/filebrowser//browse?resourcepath=User_Assets&directory=&settings=1&

And if I try to access the Json API from within the admin I also get a 404.

Any ideas</div>

**Comment by grantshepert** [comment]
is this still an issue?
