### ISSUE TITLE
Components not showing html area or body area.

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#126]
This component is just a basic component that should have an editor for the basic body area.  When I go to any component that should have the body area showing, it doesn't show.  I have a site we use many components on, which is important to continue the upgrade to MASA. 

![image](https://user-images.githubusercontent.com/1850313/188723926-2aff6a8e-ef07-4be5-9190-5949672b3d06.png)

**Comment by grantshepert** [comment]
Can you upload the component? Hard to debug/identify the issue otherwise.

**Comment by Tigerlady** [comment]
I think I was having an issue with a browser plugin blocking something.
