### ISSUE TITLE
Database error when updating to 7.4.0 Beta 2

### ISSUE THREAD

**Issue by jimblesphere** [MasaCMS/MasaCMS#138]
I successfully updated Masa 7.3.8 core to 7.4.0 Beta 2 using the Update Masa CMS Core function in the administrator. The site would not reload following the update. I traced the problem to this error in the ColdFusion application.log:

"Information","ajp-nio-127.0.0.1-8020-exec-1","10/20/22","15:28:24","MURA6BC982BE6271F16439AA1C2DE18B26E0","{""Suppressed"":[],""Sql"":""ALTER TABLE tcontentpublicsubmissionapprovals\n\t\t\t\t\t\tADD CONSTRAINT pk_tcontentpublicsubmissionapprovals PRIMARY KEY (contentID,siteID)"",""SQLState"":""HY000"",""Exceptions"":[{""message"":""[Macromedia][SQLServer JDBC Driver][SQLServer]Cannot define PRIMARY KEY constraint on nullable column in table 'tcontentpublicsubmissionapprovals'."",""class"":""java.sql.SQLException""}...

I got around the error by manually setting the siteid column in the SQL Server database table to not allow nulls. After restarting the application, the site loaded. I did not attempt to find why this column was set as nullable in the first place.

**Comment by grantshepert** [comment]
It's likely that the db update script that runs during startup failed for some reason. I haven't encountered this in recent updates, so it might be a one-off.

**Comment by guustnieuwenhuis** [comment]
Since this is a issue related to a beta version and I'm not aware this issue repeated on the final release, I'm closing the ticket. If this issue still occurs, pleas reopen the ticket.
