### ISSUE TITLE
Errors in filebrowser.cfm in 7.4.0 Beta 2

### ISSUE THREAD

**Issue by jimblesphere** [MasaCMS/MasaCMS#139]
Error 1: The template /core/vendor/ckeditor/plugins/murafilebrowser/filebrowser.cfm attempts to load /{admin directory}/assets/css/fonts.min.css but this file could not be found anywhere. 

Error 2: filebrowser.cfm throws JavaScript errors:
Uncaught referenceError: Mura is not defined 
at https://site.com/core/vendor/ckeditor/plugins/murafilebrowser/filebrowser.cfm?type=Images&CKEditor=body&CKEditorFuncNum=46&langCode=en

This error happens because the file {admin directory}/assets/js/mura.min.js is empty. Copying the contents of mura.js into this empty file fixes this issue. 

Error 3: After correcting the mura.min.js error, filebrowser.cfm throws this error:
ReferenceError: $ is not defined @ sysusers/assets/js/vue.min.js:6

I am able to browse files and insert an image into a page using filebrowser.cfm despite the remaining uncorrected errors.

**Comment by AlHolden** [comment]
FYI, the "empty min js file" issue is also mentioned in this thread.
https://github.com/MasaCMS/MasaCMS/discussions/132

**Comment by grantshepert** [comment]
Discovered an issue last week with the minification pipeline creating empty files; should be resolved shortly.

**Comment by guustnieuwenhuis** [comment]
Issue is resolved.
