### ISSUE TITLE
Missing edit/view in file browser.

### ISSUE THREAD

**Issue by Trashami** [MasaCMS/MasaCMS#140]
I am on [Core Version 7.3.9] with a fresh install on MSSQL 19 and Lucee. Not everything runs without errors but my file browser window is missing any modal view/edit of data. The option doesn't appear at all. When I select download of a file it gives me an 404 page missing error. I noticed the previous issues with file browser and it appears all my files are present and contain content.

**Comment by grantshepert** [comment]
Are the console or network tabs in your browser showing any errors?

**Comment by Trashami** [comment]
No errors.

**Comment by AlHolden** [comment]
Other known discussions on File Browser are 58, 83, 132, 139.
I mention them here in case one or more of them have something in common.

**Comment by guustnieuwenhuis** [comment]
issue is resolved.
