### ISSUE TITLE
2E25136 gets changed to "∞"

### ISSUE THREAD

**Issue by MisterRich** [MasaCMS/MasaCMS#144]
If I put in 2E2513 or most 2E251x it gets changed to "∞"

**Comment by PeterBowater** [comment]
In which area of the CMS?

**Comment by MisterRich** [comment]
In any text field.  Page Title will do it.

**Comment by jeroenweareorangeeu** [comment]
Hello @MisterRich
Is this issue still relevant or did you find a solution?
This ticket will be closed after 30th September 2024 if no further comment is provided.

Greetings,

Jeroen

**Comment by jeroenweareorangeeu** [comment]
Ticket closed after inactivity.
