### ISSUE TITLE
key [columns] doesn't exist

### ISSUE THREAD

**Issue by MisterRich** [MasaCMS/MasaCMS#149]
I have several ORM modules that cause this error: key [columns] doesn't exist
It appears to be in the function private function caseInsensitiveOrderBy(required orderBy) output=false { in the beanFeed.cfc
I am trying to determine if this is a bug or if there is something in the ORM that causes it. 
Adding && structkeyexists(application.objectMappings[table],"columns") to line 762 of beanfeed.cfc  resolves the issue, but not sure if that will be causing other issues.

codePrintHTML	
string	780: column = listrest(column, &quot;.&quot;);<br> 781: }<br> <b>782: if ( len(column) &amp;&amp; structkeyexists(application.objectMappings, table) &amp;&amp; structkeyexists(application.objectMappings[table][&quot;columns&quot;], column) &amp;&amp; listfindnocase(&quot;char,varchar&quot;, application.objectMappings[table][&quot;columns&quot;][column][&quot;dataType&quot;]) ) {</b><br> 783: orderByList = listappend(orderByList, &quot;lower(&quot; &amp; column &amp; &quot;) &quot; &amp; listrest(orderByValue, &quot; &quot;));<br> 784: } else {<br>

codePrintPlain	
string	780: column = listrest(column, "."); 781: } 782: if ( len(column) && structkeyexists(application.objectMappings, table) && structkeyexists(application.objectMappings[table]["columns"], column) && listfindnocase("char,varchar", application.objectMappings[table]["columns"][column]["dataType"]) ) { 783: orderByList = listappend(orderByList, "lower(" & column & ") " & listrest(orderByValue, " ")); 784: } else {

column	
number	0

id	
string	??

line	
number	782

Raw_Trace	
string	bean.beanfeed_cfc$cf.udfCall8(/mura/bean/beanFeed.cfc:782)

template	
string	D:\ComplyINSHub\Demo3\www\core\mura\bean\beanFeed.cfc

type	
string	cfml
![MasaColumnsError2](https://user-images.githubusercontent.com/4364694/210569055-5496e9e8-785a-4b10-bdf9-259d4b63a3d0.png)
![MasaColumnsError](https://user-images.githubusercontent.com/4364694/210569060-e3e7a3c2-bc2b-42ef-972e-5f33835c3909.png)

**Comment by grantshepert** [comment]
To be compatible with Masa ORM there needs to be an "orderby" in the table/object, numeric, with a default of 0.

**Comment by MisterRich** [comment]
@grantshepert, just to be clear, I added the following in the 
property name="orderby" datatype="numeric" default="0";
verified it was in the table and populated to 0 and it still gives the same error. 
It does not seem to happen on all the ORM object I have just some

**Comment by jeroenweareorangeeu** [comment]
Hello @MisterRich 
Is this issue still relevant or did you find a solution?
This ticket will be closed after 30th September 2024 if no further comment is provided.

Greetings,

Jeroen

**Comment by jeroenweareorangeeu** [comment]
Ticket closed after inactivity.
