### ISSUE TITLE
Commandbox unable to pull 7.4.0 from github on install

### ISSUE THREAD

**Issue by JasPanesar** [MasaCMS/MasaCMS#156]
**Issue:**. 

**box install masacms** fails to locate the target url for 7.4.0 to download the code.

**Temporary Workaround:** 

I installed Masa 7.3.8 using the following command for now.
_box install masacms@7.3.8_

**Error details**

`
laptop:masacms admin$ **box install masacms**
 × | Installing package [forgebox:masacms]   |----------------------------------------------------   | Verifying package 'masacms' in forgebox, please wait...   | Installing version [7.4.0].
   | Verified entry in forgebox: 'masacms'
   | Deferring to [https] endpoint for forgebox entry [masacms]...
   | Downloading [HTTPS://github.com/MasaCMS/MasaCMS/archive/refs/tags/7.4.0.zip]
   | Redirecting to: 'https://codeload.github.com/MasaCMS/MasaCMS/zip/refs/tags/7.4.0'...
   |----------------------------------------------------

ERROR (5.6.1+00618)

404 Not Found https://codeload.github.com/MasaCMS/MasaCMS/zip/refs/tags/7.4.0
`

**Comment by guustnieuwenhuis** [comment]
This was a temp hick-up that should be fixed meanwhile. Some config on GitHub was missing. :)
