### ISSUE TITLE
Hard-coded directory location for admin assets

### ISSUE THREAD

**Issue by jimblesphere** [MasaCMS/MasaCMS#158]
We use a non-standard location for our admin directory, as defined by the admindir parameter in config/settings.ini.cfm. The update script for Masa 7.4 correctly installed all admin assets under this directory. However, some scripts in this directory have hard-coded references to the admin folder instead of using the custom directory. We have found this problem in:

{admin directory}/core/views/carch/scaffold.cfm
{admin directory}/core/views/scaffold/assembler.cfm

For example, scaffold.cfm has this <script> tag:

<script src="#$.globalConfig('rootPath')#/admin/assets/js/scaffold/scaffolder.min.js"></script>

Our quick workaround to get around this problem was to copy the assets folder from our custom location into admin/assets. This is not the first update where we have had to do this. Needing to resort to this workaround is obviously not ideal. This same problem (or similar) may well exist in other locations, but this is where it has caused problems for us. This should not be a difficult fix in the specific scripts I found but if it's a more widespread problem then maybe a more strategic solution should be found.

**Comment by guustnieuwenhuis** [comment]
fixed in version 7.4.1 by PR #177
