### ISSUE TITLE
Upgrading site from Mura 7.0 to Masa latest release. Throws Zip Error

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#166]
I have a site that I have been trying to update to the latest MASA version.  The site is on 7.0 of Mura.  I have followed the instructions on the old MURA Docs for updating to 7.2, which several have mentioned here. I have replaced the MURA zip with the MASA zip here on GitHub.  

When I try to do the update, I get a Zip error.  Below is the error dump that I am getting.  I am stuck on this as it is the only site I have had this issue when updating to date.  

string	error in opening zip file
Array
1	
Struct
codePrintHTML	
string	518: <br> 519: /* Open Zip file */<br> <b>520: zipFile.init(arguments.zipFilePath);</b><br> 521: <br> 522: /* Zip file entries */<br>
codePrintPlain	
string	518: 519: /* Open Zip file */ 520: zipFile.init(arguments.zipFilePath); 521: 522: /* Zip file entries */
column	
number	0
id	
string	??
line	
number	520
Raw_Trace	
string	zip_cfc$cf.udfCall(/mura/Zip.cfc:520)
template	
string	E:\Websites\dev.mysite.org\www\requirements\mura\Zip.cfc
type	
string	cfml
2	
Struct
codePrintHTML	
string	114: <br> 115: &lt;cfif len(diff)&gt;<br> <b>116: &lt;cfset rs=zipUtil.list(&quot;#currentDir##zipFileName#.zip&quot;)&gt;</b><br> 117: <br> 118: &lt;cfif directoryExists(&quot;#currentDir##zipFileName#&quot;)&gt;<br>
codePrintPlain	
string	114: 115: <cfif len(diff)> 116: <cfset rs=zipUtil.list("#currentDir##zipFileName#.zip")> 117: 118: <cfif directoryExists("#currentDir##zipFileName#")>
column	
number	0
id	
string	??
line	
number	116
Raw_Trace	
string	autoupdater.autoupdater_cfc$cf.udfCall(/mura/autoUpdater/autoUpdater.cfc:116)
template	
string	E:\Websites\dev.mysite.org\www\requirements\mura\autoUpdater\autoUpdater.cfc
type	
string	cfml
3	
Struct
codePrintHTML	
string	383: &lt;cftry&gt;<br> 384: &lt;cfif rc.$.validateCSRFTokens(context='updatecore')&gt;<br> <b>385: &lt;cfset updated=application.autoUpdater.update()&gt;</b><br> 386: &lt;cfset files=updated.files&gt;<br> 387: &lt;cfelse&gt;<br>
codePrintPlain	
string	383: <cftry> 384: <cfif rc.$.validateCSRFTokens(context='updatecore')> 385: <cfset updated=application.autoUpdater.update()> 386: <cfset files=updated.files> 387: <cfelse>
column	
number	0
id	
string	??
line	
number	385
Raw_Trace	
string	admin.core.views.csettings.list_cfm$cf$c8w.call(/muraWRM/admin/core/views/csettings/list.cfm:385)
template	
string	E:\Websites\dev.mysite.org\www\admin\core\views\csettings\list.cfm
type	
string	cfml
4	
Struct
codePrintHTML	
string	1536: &lt;/cfif&gt;<br> 1537: <br> <b>1538: &lt;cfsavecontent variable='response'&gt;&lt;cfinclude template=&quot;#viewPath#&quot;/&gt;&lt;/cfsavecontent&gt;</b><br> 1539: <br> 1540: &lt;cfreturn response /&gt;<br>
codePrintPlain	
string	1536: </cfif> 1537: 1538: <cfsavecontent variable='response'><cfinclude template="#viewPath#"/></cfsavecontent> 1539: 1540: <cfreturn response />
column	
number	0
id	
string	??
line	
number	1538
Raw_Trace	
string	admin.framework_cfc$cf.udfCall7(/admin/framework.cfc:1538)
template	
string	E:\Websites\dev.mysite.org\www\admin\framework.cfc
type	
string	cfml
5	
Struct
codePrintHTML	
string	546: <br> 547: if ( structKeyExists(request, 'view') ) {<br> <b>548: out = internalView( request.view );</b><br> 549: } else {<br> 550: out = onMissingView( request.context );<br>
codePrintPlain	
string	546: 547: if ( structKeyExists(request, 'view') ) { 548: out = internalView( request.view ); 549: } else { 550: out = onMissingView( request.context );
column	
number	0
id	
string	??
line	
number	548
Raw_Trace	
string	admin.framework_cfc$cf.udfCall2(/admin/framework.cfc:548)
template	
string	E:\Websites\dev.mysite.org\www\admin\framework.cfc
type	
string	cfml

**Comment by tomchiverton** [comment]
Just to be clear, you are doing https://docs.murasoftware.com/v7-1/installation-setup/upgrading-mura/#section-upgrade-an-existing-installation-directory using https://github.com/MasaCMS/MasaCMS/archive/refs/tags/7.2.0.zip in place of https://github.com/blueriver/MuraCMS/archive/7.1.zip ?
