### ISSUE TITLE
Trying to get a plugin to work in Masa

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#168]
Hello everyone. I wasn't sure where to post this, but I decided to start here.  I have an old plugin that I am trying to get up to date to work in Masa.  It is a chamber membership site that wants extra data for its members.  They regularly download information in a spreadsheet, so I built a custom plugin years ago.  We are now trying to get them updated to Masa, and I have most of the pieces working except when trying to get the details onto the page.  

So I have created a member page that I then go to the inline edit and drop the plugin into the page.  The query for the plugin works, and I see the member in the list. 
![image](https://user-images.githubusercontent.com/1850313/217865186-401a73f8-f38f-4389-812e-e75cbb6f0fbc.png)

As you can see, I get results from the database for the member.  However, when I try to apply, I get a 500 error. 

Error on page

500 Error
The key [MEMBER_ID] does not exist, only the following keys are available: [ASYNC, class, contentcssclass, contentcssid, cssclass, inited, instanceid, moduleid, name, object, objecticonclass, OBJECTID, objectname, RENDER, stylesupport].
Code: 0
Type: 0
Column: 0
ID: ??
Line: 44
Raw Trace: cwmembers.contentobjects.contentobjects_cfc$cf.udfCall(/plugins/CWMembers/contentObjects/contentObjects.cfc:44)

So in the content object file I have this code.

	
	// 	Page: Member DETAILS
	public any function dspCWMemberDetails($){
		// collect values from configurator form
		var Member_id = $.event('objectParams').Member_id;
		// return function stored in plugins/CWMembers/eventHandlers/eventHandler.cfc
		return $.cwDisplayMemberDetails(
			Member_id=Member_id
			);
	}
The configurator file has this.

<cfscript>
	$=application.serviceFactory.getBean("MasaScope").init(session.siteID);
		
	params=$.event("params");
		
	if(isJSON(params)){
		params=deserializeJSON(params);
	} else {
		params=structNew();
	}
	// default for Member ID		
	if(not structKeyExists(params,"Member_id")){
		params.Member_id="0";
	}
	// listMembers array is stored in CW application scope, convert to list sorted by name
	membList = arrayToList(structSort(application.cwdata.listmembers,'textNoCase'));
</cfscript>

<cfparam name="form.Member_id" default="#params.member_id#">

<cfoutput>
  <div id="availableObjectParams"	
		data-object="plugin" 
		data-name="CWMembers Member Details Page" 
		data-objectid="#$.event('objectID')#">
    <dl class="singleColumn">
      <dt>Select Member</dt>
      <dd> 
        
        <select name="Member_id" class="objectParam">
          <option value="0">Select a Member</option>
          <cfloop list="#membList#" index="pp">
            <option value="#pp#"<cfif pp eq form.Member_id> selected="selected"</cfif>>#application.cwdata.listMembers[pp]#</option>
          </cfloop>
        </select>
      </dd>
    </dl>
  </div>
</cfoutput>

Again, I get the members list to show up in te drop-down but can't seem to get the information to display on the page.  I have several of these types of pages for categories, new members, etc.  If I can get even one of them to work, I know I can get the rest to fall into line. I am unsure which piece of the puzzle I am missing to get Masa to pick up the Member id etc.

**Comment by withLogic** [comment]
Does this plugin work properly on an older version of MuraCMS? Are you having the same issues?

**Comment by Tigerlady** [comment]
Ok, so this plugin worked on Mura 7.0.7 before the new layout came into play.  I would prefer to do this on the back side of the admin, not the front layout, but not sure how to get plugins to work in the Extended Attributes.
Here is a screenshot of adding a member to the current Mura 7.0.7.  The chamber has now merged with another chamber, and they liked how the members worked on the old site.  I just need a little help here to get the plugin to work with the New Mura layout.  

![image](https://user-images.githubusercontent.com/1850313/225405604-c4b4ddbd-3609-46ad-95c6-c33e5633797c.png)

**Comment by Tigerlady** [comment]
went in a different direction
