### ISSUE TITLE
StructKeyDelete is no cfml function

### ISSUE THREAD

**Issue by guustnieuwenhuis** [MasaCMS/MasaCMS#176]
https://github.com/MasaCMS/MasaCMS/blob/ea9dd65d88ba55d5b41131cf355778a6529ff42a/core/appcfc/onMissingTemplate_include.cfm#L95

**Comment by ejespersen-AMS** [comment]
https://gist.github.com/ejespersen-AMS/b421126d85846c6125fc728933274647
