### ISSUE TITLE
Can't type an & in title without it changing it to &amp;  on edit

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#179]
When typing a title the first time, you can put in an &; however, if you go back to edit it, the & turns into "&amp; " and I then have to delete the rest.  I also have to clear other titles, so the nav and href get put in correctly. 

I have been using & for quite a while now in titles without issues. I am currently on 7.4.0 version.  Thank you.

**Comment by guustnieuwenhuis** [comment]
Hi @Tigerlady,
Could you retest on the latest version of Masa CMS? We've made some changes in version 7.4.2 that might have fixed this. I wasn't able to reproduce the issue.
If it hasn't been fixed, could you provide me with some detailed steps to reproduce and a few screenshots?

**Comment by Tigerlady** [comment]
Guust, This seems to have been fixed in the 7.4.2 update.  I have updated a few to the 7.4.3, and it still seems fine.  Thank you.
