### ISSUE TITLE
Update To 7.4.1

### ISSUE THREAD

**Issue by MisterRich** [MasaCMS/MasaCMS#184]
In using the update core feature it returns Can't delete file [[my path removed]\www\Application.cfc]

**Comment by jeroenweareorangeeu** [comment]
Hello @MisterRich 
Is this issue still relevant or did you find a solution?
This ticket will be closed after 30th September 2024 if no further comment is provided.

Greetings,

Jeroen

**Comment by jeroenweareorangeeu** [comment]
Ticket closed after inactivity.
