### ISSUE TITLE
7.4.1 window.location not working

### ISSUE THREAD

**Issue by MisterRich** [MasaCMS/MasaCMS#186]
Not sure how to explain this.  I have several pages and forms that after being submitted use the simple javascript window.location to redirect the user to a different page.  This works fine in 7.4.0 (and previous versions) but in 7.4.1 it does not seem to work at all.  I don't see any obvious errors as to why.

**Comment by Tigerlady** [comment]
I haven't done window.location for redirection on forms. I use redirect_url, as a hidden field.
![image](https://user-images.githubusercontent.com/1850313/234919754-8851b248-c334-4c83-a477-e5b44c52d39c.png)

**Comment by MisterRich** [comment]
I was able to detemine th issue to be when a form in an ORM Module page is submitted in 7.4.0 it is submited with the flag ASYNC = false, in 7.4.1 it is ASYNC = true.

**Comment by jeroenweareorangeeu** [comment]
Ticket closed after inactivity.
