### ISSUE TITLE
Error Updating to latest version

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#188]
I just tried updating a development site that I have running on Lucee and it threw this error.

string | Can't delete file [E:\Websites\mywebsite.com\www\core\vendor\lib\diff_match_patch.jar]

**Comment by jeroenweareorangeeu** [comment]
Hello @Tigerlady,

Is this issue still relevant or did you find a solution?
This ticket will be closed after 30th September 2024 if no further comment is provided.

Greetings,

Jeroen
