### ISSUE TITLE
cannot create related content set on class extension - entity type instead of page type

### ISSUE THREAD

**Issue by ptutty** [MasaCMS/MasaCMS#195]
![Screenshot 2023-06-15 at 14 16 31](https://github.com/MasaCMS/MasaCMS/assets/978825/491b4683-f532-457f-946c-46d3f32b2488)

**Comment by ptutty** [comment]
I've fixed this issue locally by replacing the file:
admin/core/views/cextend/editrelatedcontentset.cfm
with the one from my old Mura 7.4 codebase. However not sure if this will break anything else? Really need a fix to be rolled into Masa as i don't want to fork the repo.

**Comment by jeroenweareorangeeu** [comment]
Hello @ptutty 

Sorry for the long, long delay.
Can you please provide the code changes in this ticket?  What dit you change?
Can you provide full URLS to changes files please.
Than we can take a look at this further. Thank you!

This ticket will be closed after 30th September 2024 if no further comment is provided.

Greetings,

Jeroen

**Comment by jeroenweareorangeeu** [comment]
Ticket closed after inactivity.
