### ISSUE TITLE
A warning before upgrading to 7.4.2...

### ISSUE THREAD

**Issue by no3rdw** [MasaCMS/MasaCMS#198]
I saw that 7.4.2 was released just an hour ago!  I have a brand new 7.4.0 install sitting around in development mode, so I thought I would try the upgrade to 7.4.2 via the Update Core within the Masa admin panel.

Editing pages via Inline Edit no longer functions.  On Publish/Save, a prompt is displayed saying: "The property named 'active' is not valid" followed by the same message for many other properties (mobileExclude, searchExclude, restricted, nextN, isNav, display, orderno, title, forceSSL, isFeature, displayTitle, and responseChart').

Adding/Editing pages via Full Edit no longer functions.  Javascript error in the console when clicking 'Save Draft', 'Preview' or 'Publish' reads: Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at Object.ckContent (architecture.min.js?coreversion=7.4.2:1:3432)
    at HTMLButtonElement.onclick (?muraAction=cArch.edit&startrow=1:2753:240)

**Comment by guustnieuwenhuis** [comment]
Hi @no3rdw,

We can confirm the first issue and we're looking into it.

Regarding the Full Edit, can you make sure your browser hasn't cached any of the javascript file?

**Comment by no3rdw** [comment]
Thanks @guustnieuwenhuis!  The 'Full Edit' issue doesn't seem to be related to caching.  It looks like the form element 'canonicalURL' is no longer part of the Edit Content form but it's still being referenced in architecture.min.js on Save/Preview/Publish.  

When I run `isValidURL(document.contentForm.canonicalURL.value)` from the browser console in a 7.4.0 install, a boolean is returned, but I get the _TypeError: Cannot read properties of undefined (reading 'value')_ message in the 7.4.2 install.

**Comment by guustnieuwenhuis** [comment]
The problem with inline editing should be fixed now, you should be able to update the core and have the fix.

Regarding the issue with the canonical URL. I do see the canonical url, except when I have `keepMetaKeywords` set to `true` in the settings.ini.cfm. If it's set to `true`, you're right that there is an issue, but not related to this release. Unless you really need that setting set to `true`, I would set it to `false`. We'll note this as an issue we'll fix asap, but could you create a separate issue for this?

**Comment by no3rdw** [comment]
@guustnieuwenhuis - The 'Full Edit' issue looks like it's specific to adding the keepMetaKeywords=true setting in settings.ini.cfm and _not_ specific to 7.4.2 - sorry about that!  I had been testing the keepMetaKeywords setting the other day and apparently never tried editing content after enabling it.

**Comment by jimblesphere** [comment]
Guust,

I am experiencing the same issue. I have reupdated the core and it is still
happening. The error message I get when trying to save in inline edit is:

The property named 'active' is not valid
The property named 'mobileExclude' is not valid
The property named 'searchExclude' is not valid
The property named 'restricted' is not valid
The property named 'nextN' is not valid
etc. etc. etc.

jim

**Comment by no3rdw** [comment]
@jimblesphere If you need a quick fix to this issue until Guust's fix is added to GitHub, you can replace line 449 in core/mura/bean/beanValidator.cfc with:

replace `return '';`
with `return arguments.object.invokeMethod("get#arguments.propertyIdentifier#");`

Not suggesting this as a permanent fix - but it allows inline edit to work until this can be fully addressed.

**Comment by jimblesphere** [comment]
Thanks! I've rolled back to 7.4.1 on our development server for the time
being and I won't update production just yet. I'll hang tight until Guust
can update GitHub.

jim
