### ISSUE TITLE
Setting keepMetaKeywords=true in settings.ini.cfm breaks content editor

### ISSUE THREAD

**Issue by no3rdw** [MasaCMS/MasaCMS#200]
Setting keepMetaKeywords=true currently adds the metaKeywords field into the content editor under the Summary tab, but also removes the 'canonicalURL' field which is referenced when saving, previewing, and publishing content.  When keepMetaKeywords is set to true, content cannot be edited due to Javascript referencing the missing canonicalURL field.  

I've submitted a pull request that modifies dsp_panel_summary to only display metaKeywords without removing canonicalURL.  Hopefully I've done this correctly - it's my first pull request.

Sorry for wrongly attributing this issue to the 7.4.2 update in my other submitted issue - this one looks like it's been around for a while.  I had just been testing out the setting a couple days ago and had not yet tried editing content once it was enabled.  

Edit: Confirming this issue does not exist in 7.3.11

**Comment by guustnieuwenhuis** [comment]
fix will be part of the 7.4.3 patch release
