### ISSUE TITLE
Issue #198 is not fixed, inline edit still does not work in 7.4.2

### ISSUE THREAD

**Issue by jimblesphere** [MasaCMS/MasaCMS#203]
Issue #198 is marked as fixed but it is not. Inline edit still does not work in 7.4.2 and contrary to the discussion thread in #198 the problem is not related to "adding the keepMetaKeywords=true setting in settings.ini.cfm," at least not on our installation. We did not have this setting in settings.ini.cfm. I tried adding keepMetaKeywords=false to see if that would resolve the issue and it did not. 

So far the only solution to this problem is the suggestion by no3rdw to replace line 449 in core/mura/bean/beanValidator.cfc with:
return arguments.object.invokeMethod("get#arguments.propertyIdentifier#");

Are there any security or functional concerns with making that change?

**Comment by guustnieuwenhuis** [comment]
The main branch has been updated, I had put the fix only on the release 7.4 branch last week.
