### ISSUE TITLE
Objects in display region become un-editable after clicking them once in Inline Editor

### ISSUE THREAD

**Issue by no3rdw** [MasaCMS/MasaCMS#206]
This is an issue that I've been working around for a while and would be great to get fixed.  (I'm not sure where to begin looking for the code that would handle this...)

When in the Inline Editor, clicking the 'Edit' button on certain objects will modify the button to no longer be functional after the first click.  To reproduce this error:

Setup a page with a 'Collection' object in an editable region, configure it _and publish changes to the page_.
Return to the Inline Edit mode on the same page and click the edit button on the collection to bring up the collection properties in the sidebar.  
You'll see a little icon with the text 'Collection' appear next to the edit button.  **[Image showing this icon and text](https://imgur.com/YuVScfA)**

Once this appears, that specific edit button is no longer functional until the page is refreshed.  Closing the properties sidebar does not fix the issue. Clicking to another object and back to the initial object does not fix the issue.  Dragging-and-dropping the object still works, but does not fix the edit button. No javascript errors are logged, the edit button just no longer has a click event on it.

This makes editing objects veeeery clunky as you need to constantly be publishing changes to the page after each individual change.  Referencing the attributes of one object to copy into another object is difficult or impossible without editing the page in two browser windows.

This issue is _not_ limited to only collections, but it's easiest to reproduce with collections.  The same thing can be triggered on a 'Text' object by clicking it and editing the content source, but this doesn't _always_ seem to trigger the issue with the edit button.

Edit: I see this issue on my live 7.4.0 install with a custom theme, and also on a development 7.4.2 install with the default theme

Editing again to confirm that this error does not exist in a fresh 7.3.11 install

**Comment by Tigerlady** [comment]
I, too, have this issue with inline editing. After adding custom text to the page and saving the page, then going back to edit the custom text, I can no longer edit it after saving the page.  When I click on the pencil icon, it doesn’t work or bring up the editor. I have several pages on the site where I have the custom text option, and none are working now. 
![editdoesnotwork](https://github.com/MasaCMS/MasaCMS/assets/1850313/c755db8e-4678-41d0-87f0-ee1c8dc8dc98)

**Comment by no3rdw** [comment]
I spent a couple hours today looking through the change history on frontendtools.js.cfm, core.js, etc trying to find what may have changed between 7.3 and 7.4 to introduce this bug, but did not have much luck yet.

It's something like: when clicking the frontEndToolsModal div to open a collection's configurator, the click event is being unbound and not rebound.  I can see where all the frontEndToolsModal click events are initialized by initFrontendUI but I'm still not sure where the difference lies for collections specifically.

BUT, I do have a workaround that makes 7.4.x usable for people who rely heavily on collection objects, like myself.  The following bookmarklet will just reinitialize the frontend editor, making collections clickable again (once) without needing to publish or save a draft.

`javascript: (() => { MuraInlineEditor.deInit();MuraInlineEditor.init(); })();`

**Comment by no3rdw** [comment]
I started digging into this a couple weeks back and unfortunately haven't had the time to continue researching it - and may not for the foreseeable future.  I wanted to pass along what I found as this bug is significant enough that it has stopped me from moving past version 7.3.11 (where this bug does not exist) despite there being some great bug fixes in the more recent versions.

- When a display object is clicked and the configurator sidebar is displayed, the 'mura-edit-icon' div on that object loses it's click event.  I cannot find where this is happening, and what _should_ be reapplying the click event, but I am pretty certain that the event that is normally triggered when this icon is clicked is Mura.initFrontendUI().
-  When a display object is clicked, the DOM object that replaces the clicked display object loses some empty _data_ attributes, notably the 'objectname' attribute - which results in the sidebar displaying 'null' as the object type.
- The 'items' data attribute on a collection begins as a string.  When a collection's display object is clicked, the 'items' data attribute gets surrounded with &quot;.  This is the case in 7.3.11 as well, but in newer versions when the object is edited a second time, it becomes double-escaped, leading to the data in this attribute being lost (so the selected items in a custom related content set are lost).  When the related content set itself is edited, the 'items' data value is replaced with an array of escaped strings, and the double-escaping is no longer an issue.  This may affect other data attributes in other types of display objects, but I have been focused mainly on collections.

So, after a bunch of trial and error, I created the following bookmarklet which can be used to 'reset' the front-end UI once one or more display objects are unclickable.  It goes through the DOM, finds each mura-object, and sets the click function to Mura.initiFrontendUI(this), which allows the object to be clicked and edited again.  It also forces the objectname data attribute to an empty string, which allows Masa to display the default object name instead of null.  And, it _removes_ double quotes from the items data attribute IF that attribute is set (not null) and a string (not an array).  This basically resets the attribute to the way it appears when the page is first loaded so Masa can just escape it again without introducing double-escaped strings.

You can create a browser bookmark with the following code as the URL, and click it anytime a display object becomes 'unclickable'.  It will fix the object once - you have to click the bookmarklet every time Masa removes the click event.  I've only tested this with collections and text display objects so far.

javascript: (() => { Mura('body').find('.mura-object').each(function(){if(typeof Mura(this).data('items') == "string") { console.log(Mura(this).data('items').replace(/"/g, '')); Mura(this).data('items', Mura(this).data('items').replace(/"/g, '')) }; Mura(this).data('objectname', '').find('.mura-edit-icon').on('click', function() {Mura.initFrontendUI(this)});}); })();
