### ISSUE TITLE
Local Index Advanced Filter loses 'Field' value when set to Category ID

### ISSUE THREAD

**Issue by no3rdw** [MasaCMS/MasaCMS#214]
**Describe the bug**
When editing a Local Index / Collection in the admin panel, adding an advanced filter with Field set to 'Category ID' and a non-UUID value into the criteria field modifies the collection to instead filter on Category _Name_ (this is existing working functionality).  But, because Category Name does not appear in the Advanced Filter 'Field' dropdown list, the next time the Local Index is edited, the Field value is lost.

The easiest fix is to add a 'Category Name' field type to the dropdown.

**To Reproduce**
Create a Local Index (Collection) in the admin
Add an Advanced Filter with 'Field' set to 'Category ID'
Enter a criteria _other than a UUID_ - this may sound like user error, but the code that builds the feed query will instead use Category Name when a non-UUID value is entered.  I use [m]$.event('varname')[/m] tags within these fields, which also works, and forces the use of Category Name instead of ID.
Save and Re-Edit the Local Index
The 'Field' field will display 'Select Field' because the value that was saved (tcontentcategories.name^varchar) does not match any values in the dropdown list.
Updating the Local Index will break the Category Name filter because the Field value will be lost on save/update.

**Expected behavior**
Advanced Filter 'Field' should be saved, not lost, on update

**Environment (please complete the following information):**
 - OS:  Windows Server
 - CFML Engine: Adobe ColdFusion 2018
 - Database: MSSQL
 - Reproducible in Masa Versions: 7.4.2 and 7.3.11

**Comment by guustnieuwenhuis** [comment]
fixed in release 7.4.3
