### ISSUE TITLE
Advanced Search for Related Content does not work

### ISSUE THREAD

**Issue by no3rdw** [MasaCMS/MasaCMS#230]
**Describe the bug**
Advanced Search for Related Content does not work

**To Reproduce**
1. Go to the 'Related Content' tab on any content object, 
2. Click 'Manage Related Content', 
3. Click the 'Advanced Search' button, 
4. Click the magnifying glass button to execute the search.  

The Ajax request throws an error because the entitytype parameter is submitted to cArch.loadRelatedContent, and appended to the ajax request by siteManager.loadRelatedContent.

**Comment by guustnieuwenhuis** [comment]
Fixed in 7.4.4
