### ISSUE TITLE
Throws Error "No matching function [PARSEXML] found

### ISSUE THREAD

**Issue by bowler865** [MasaCMS/MasaCMS#242]
https://github.com/MasaCMS/MasaCMS/blob/2ef41b22388ce3e625d4248e994e84ddafc12dfe/core/appcfc/onApplicationStart_include.cfm#L837

Updating this function to xmlParse resolved the issue.

**Comment by jochemd** [comment]
Making that change introduces [an XXE vulnerability](https://owasp.org/www-community/vulnerabilities/XML_External_Entity_(XXE)_Processing) so is not recommended.

The real question is why parseXML() was not found, as it is a function that was added to the compatibility layer: https://github.com/MasaCMS/MasaCMS/blob/2ef41b22388ce3e625d4248e994e84ddafc12dfe/core/mura/backport/acf.cfm#L6

Do you have a description of what you were doing and a stack trace so we might be able to investigate in which access path the function is not loaded?

**Comment by bowler865** [comment]
My customer ran into the issue when trying to use the url alias plugin which was working fine in Mura 7.1.

**Comment by guustnieuwenhuis** [comment]
Hi @bowler865,
Do you have a stacktrace for us? Or steps to reproduce?
Is the plugin you're using a open source one we could test? If so, can you share a link to the code?
Kind regards,
Guust

**Comment by jeroenweareorangeeu** [comment]
Hello @bowler865 

Is this issue still relevant or did you find a solution?
This ticket will be closed after 30th September 2024 if no further comment is provided.

Greetings,

Jeroen

**Comment by jeroenweareorangeeu** [comment]
Ticket closed after inactivity.
