### ISSUE TITLE
Uncaught TypeError: a.contentWindow is null when updating Caption or Credits on "Edit Image Properties" window.

### ISSUE THREAD

**Issue by russianlife** [MasaCMS/MasaCMS#247]
**Describe the bug**

When I try to add a caption, credit, or alt value to a main associated image, it will not save the record.

**To Reproduce**
Try to add any of these values to associated image.

Confirmed it is not browser dependent.

**Comment by guustnieuwenhuis** [comment]
We can reproduce this issue.

Some extra info:
* The issue already occurs already when opening the image properties modal, even if you don't change and don't save.
* The first error happens when closing the image properties modal, the rest of the errors are a side effect of that first one.

**Comment by guustnieuwenhuis** [comment]
Issue will be fixed in release 7.4.5
