### ISSUE TITLE
Can't set (optional) Release date - not being written to database

### ISSUE THREAD

**Issue by tbugler70** [MasaCMS/MasaCMS#248]
**Describe the bug**
When i attempt to set the optional field of Release Date under Publishing, it does not work. When I save the page and reopen the release date is empty. I am using release date in a collection to display the date items were published.

**To Reproduce**
1. go to page you want to edit and set the release date
2. select the Publishing tab
3. Set the release date
4. Save the page

**Expected behavior**
Expect the release date value to be saved

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome, firefox,edge,safari
 - Version latest versions of all

**Environment (please complete the following information):**
 - MASA 7.4 (issue also existed in 7.3)
 - OS: Linux
  - CFML Engine Lucee 5.4
 - Database MySQL

**Additional context**
This is a site that was updated from Mura 7.0.
Current site is MASA 7.4
![masa](https://github.com/MasaCMS/MasaCMS/assets/50739362/d2e77f4a-e4d0-4bf1-86d8-e936dde36d0f)

**Comment by tbugler70** [comment]
As a work around I have added a class extension of Release Date which appears to be working - just not sure why the builtin release date is not working as expected.

**Comment by guustnieuwenhuis** [comment]
What exact version of 7.4 are you using? We've tested on 7.4.4 and were not able to reproduce the issue.

Something tells me this was an issue and we've fixed it, but I can't find the details on the issue/fix.

**Comment by ptutty** [comment]
I get the same, even after upgrading to 7.4.4. 

any fields, out of the box(release date, expires etc,) or class extensions that are set using the calender popup do not persist after saving. They are in the DB but do not appear in the UI.
<img width="367" alt="Screenshot 2023-10-24 at 15 33 30" src="https://github.com/MasaCMS/MasaCMS/assets/978825/82af63ca-3398-4e4d-90d0-c558fd67b515">

**Comment by ptutty** [comment]
I've managed to fix this issue for our env cf2021

![Uploading Screenshot 2023-11-07 at 13.21.15.png…]()
