### ISSUE TITLE
Calendar not showing events.

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#251]
**Describe the bug**
When I add an event to the calendar as a calendar event the large monthly calendar doesn't show the event on the date.  This used to work. 

**To Reproduce**
1. [Go to '...'](https://www.grandchamber.org/events/)
2. It says there are no events scheduled at this time; however, I have an event scheduled for November 2nd, and the only way I can get it to show up in the navigation is to do a collection.   

**Expected behavior**
When I add an event, the left-hand navigation of Calendar should show the event.  
The calendar should show the event on the calendar. 

**Screenshots**
![image](https://github.com/MasaCMS/MasaCMS/assets/1850313/48d2d4d1-837e-424a-8f7f-544c82187b1f)

![image](https://github.com/MasaCMS/MasaCMS/assets/1850313/f2e0093f-0c78-46e0-bb1b-b90b8383fd81)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [doesn't matter the browser]
 - Version [[Core Version 7.4.3]

**Environment (please complete the following information):**
 - OS: [Windows Server]
 - CFML Engine [Lucee 5.4]
 - Database [ MSSQL]

one more thing when I try to add a page as a calendar item I get the following SQL error
500 Error
String or binary data would be truncated.
Datasource:myDSN
SQL:INSERT INTO tcontent (ContentHistID, ContentID, Active, OrderNo, approved, DisplayStart, displaystop, MetaDesc, MetaKeyWords, Body, Summary, path, tags, responseMessage, responseDisplayFields, Title, menuTitle, filename, LastUpdate, Display, ParentID, Type, subType,LastUpdateBy, LastUpdateByID, siteid, moduleid, isnav, restricted, target, restrictgroups,template, responseChart,responseSendTo,moduleAssign,notes,inheritObjects,isFeature, releaseDate,targetParams,isLocked,nextN,sortBy,sortDirection,featureStart,featureStop,fileID,forceSSL, remoteID,remoteURL,remotePubDate,remoteSource,RemoteSourceURL,Credits, audience, keyPoints, searchExclude, displayTitle, doCache, created, urltitle, htmltitle, mobileExclude, changesetID, imageSize, imageHeight, imageWidth, childTemplate, majorVersion, minorVersion, expires, displayInterval ,objectParams) VALUES ( '4BFB37F2-2AAC-4BE7-AA15AD1DA4835F1D', '5F5E1929-17A2-426B-A314AE5711F8FF90', 1, 1, 1, {ts '2023-11-14 17:30:00'} , {ts '2023-11-14 19:30:00'} , null, null, '<p>Details Coming Soon</p> <p>Date: Tuesday, November 14, 2023&nbsp;</p> <p>Time: 5:30 PM</p>' , null, '00000000000000000000000000000000001,47E126F0-63C2-455C-AD41A81D84EC8C63,5F5E1929-17A2-426B-A314AE5711F8FF90', null, null, null, 'Melrose Eye Car Ribbon Cutting', 'Melrose Eye Car Ribbon Cutting', 'events/melrose-eye-car-ribbon-cutting' , {ts '2023-10-26 13:16:05'}, 2, '47E126F0-63C2-455C-AD41A81D84EC8C63', 'Calendar', 'Default', 'Barbara Renowden', '66636529-5FF3-40FA-B926A18E6E86481C', 'default', '00000000000000000000000000000000000', 1, 0, '_self', null, null, 0, null, null, null, 'Inherit', 0, null , Null , 0, 10, 'orderno', 'asc', null , null , null, 0, null, null, null, null, null, null, null, null, 0, 0, 1, {ts '2023-10-26 13:16:05'} , 'melrose-eye-car-ribbon-cutting', 'Melrose Eye Car Ribbon Cutting', 0, null, 'small', 'AUTO', 'AUTO', null, 0, 0, null , '{"repeats":0,"detectconflicts":0,"detectspan":"12","allday":0,"timezone":"America/Chicago","every":"1","type":"daily","end":"on","endon":"November, 14 2023 00:00:00 -0600","endafter":"0","daysofweek":""}', '{}' )

I can give you the full dump of the error if you like.

**Comment by Tigerlady** [comment]
After doing some digging, I think it is the "displayInterval", field in the database that has the issue.  The character count is set to 200. When you select a longer month name like November or any other long name the data will not fit in the field.  I added an item in a shorter month name of May with a start and end time, and it did get put into the database. 

The "tcontent" table needs to be changed to handle more than 200 max characters for the "displayInterval" field. 

I still have an error on not getting items to show on the front-end calendar page. 
![image](https://github.com/MasaCMS/MasaCMS/assets/1850313/678b343b-f36d-4dec-9e75-38d69d51703a)

Any ideas on how to update the field in the database without losing all my data?

**Comment by Tigerlady** [comment]
One more thing that I just found while trying to debug this issue.  
This error is in my Lucee logs 
"ERROR","ajp-nio-127.0.0.1-8116-exec-345","10/27/2023","11:11:40","muraD158BFBF7AF2D971AE44596753513521", "lucee.runtime.exp.CasterException: cannot cast **[2024-06-09] string to a number value**
at lucee.runtime.op.Caster.toDoubleValue(Caster.java:479)
at lucee.runtime.op.Caster.toDoubleValue(Caster.java:402)
at content.contentcalendarutilitybean_cfc$cf$4ic7.udfCall(/mura/content/contentCalendarUtilityBean. cfc:74)

On line 74 of the Calendar Utility Been
` // End Date
    if ( !IsDate(arguments.end) || ( IsDate(arguments.end) && Fix(arguments.end) < Fix(arguments.start) )  ) {
      arguments.end = CreateDate(Year(arguments.start), Month(arguments.start), DaysInMonth(arguments.start));
    }`

**Comment by Tigerlady** [comment]
Any word on how to fix this?

**Comment by guustnieuwenhuis** [comment]
This issue has been fixed in version 7.4.5.
