### ISSUE TITLE
Update to the latest release CFSET not closed

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#274]
**Describe the bug**
Updated to the latest release and get this error:

failure in E:\Websites\dev.mysite.com\www\core\mura\configBean.cfc;tag [cfset] is not closed

**To Reproduce**
Update to [Core Version 7.4.5]
Go to the front end of the site and get this error. 

The configBean.cfc was missing the closing quote " <cfset variables.instance.version="7.4.5/>

Once I added it, the site worked.

**Comment by jeroenweareorangeeu** [comment]
Thanks for this report. It has been fixed in the github repository. If you want you can pull again and it should work.

**Comment by jeroenweareorangeeu** [comment]
Fixed.
