### ISSUE TITLE
bug in masa 7.4.5 changes

### ISSUE THREAD

**Issue by ptutty** [MasaCMS/MasaCMS#282]
https://github.com/MasaCMS/MasaCMS/pull/281

adding #arguments.type#apiUtility(siteid=.... (edited) 

which evaluated to the file jsonapiUtility.cfc.....

BUT the file is jsonApiUtility.cfc

it worked with original because the file was apiUtility (lowercase 'a') they added the type to the filename and renamed the file but in doing so made the a uppercase

**Comment by ptutty** [comment]
see my pull request for fix

**Comment by jeroenweareorangeeu** [comment]
Accepted your PR.
This will be part of the 7.4.7 release.
