### ISSUE TITLE
Broken Object tags and Iframe / embed

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#289]
**Describe the bug**
I updated one of our primary customer sites to the latest security fix, and it has broken several key features. Specifically, the MASA Translator and pages that use iframes to show YouTube videos have been broken along with other places that use the word metal.  They are a screw manufacturer and this word is used all over the place. 

----------

I use the MASA Translator and this is what shows now after the upgrade
`<div class="mura-[INVALID]" data-[invalid]="muratranslationsnavtools" data-[invalid]id="" data-instanceid="F08C1B44-C6AA-4B8E-88F74CE9C571E17C" style="" data-render="server" data-async="false" data-cssstyles="" data-[invalid]iconclass="mi-commenting" data-[invalid]name="" data-masatranslationstooltype="list"><div id="" class="mura-[INVALID]-content" style=""><div class="translations-nav navSecondary plugIn showFlags">`

This is what it should show.  

`<div class="mura-object mura-async-object" data-object="muratranslationsnavtools" data-objectid="" data-instanceid="12308FB1-73E5-42BB-AD3B6D6581A5C71D" data-render="server" data-async="false" data-cssstyles="" data-objecticonclass="mi-commenting" data-objectname="" data-masatranslationstooltype="list"><div class="mura-object-content"><div class="translations-nav navSecondary plugIn showFlags">`

Also, I have a lot of videos that are shown on YouTube on this site.  

So I use a no-cookie url from YouTube.  in an iframe

`<iframe allowfullscreen="allowfullscreen" class="ui-droppable" data-cookieconsent="statistics" height="315" src="https://www.youtube-nocookie.com/embed/yp7AJR9WNYo?rel=0" width="100%"></iframe>`

It is also affecting standard words.

`<strong>Light [INVALID]ls</strong>`
`<strong>Light Metals</strong></a>`
As you can see the word meta is being stripped out of the word Metals.

My site is now very broken. 

Now, after the upgrade, I get an  [INVALID]

How do I get back these functionalities?

**Comment by guustnieuwenhuis** [comment]
Check the ENABLEDYNAMICCONTENTconfig option. You might need to change the value to 'true' in your settings file.

https://docs.masacms.com/getting-started/configuration/configuration-file/#enabledynamiccontent

**Comment by Tigerlady** [comment]
Thank you for getting back to me so quickly.  I have applied the enabledynamiccontent to the settings ini file and things are working on another site that I did the update to.  I now need to remember to add this to the settings ini file for everysite that uses Youtube. I am still not sure why it broke just a regular word like Metal.

**Comment by guustnieuwenhuis** [comment]
Since 'meta' is replace as part of that functionality.

**Comment by Tigerlady** [comment]
This one threw me for a loop this morning when I updated from [Core Version 7.4.5] to today's security fix.  I didn't have the issue on 7.4.5.  Again, thank you for answering so quickly.  I did roll back the site and will have to re-update. I did test on a different dev site and it worked.  I will have to keep this in mind for other sites that I will be updating over the next few days.
