### ISSUE TITLE
Certain words replaced in page content with [INVALID] in 7.4.6

### ISSUE THREAD

**Issue by michael-hldl** [MasaCMS/MasaCMS#292]
**Describe the bug**
Any text in a pages $.content('body') that matches the regex `(script|object|applet|embed|layer|ilayer|frameset|param|meta|base|xss|marquee)` is replaced by the string `[INVALID]`. For example the word 'based' in the main content of a page it will be rendered [INVALID]d when output.

**To Reproduce**
1. Edit the Home page in Admin - Content
2. Enter any or all of the words in this list "script,object,applet,embed,layer,ilayer,frameset,param,meta,base,xss,marquee"
3. Publish the page
4. In Admin - Content, click on View in the Home page's pop up menu

**Expected behavior**
These strings should not be replaced in page content. 

**Screenshots**
![Screenshot 2024-03-08 at 01 29 38](https://github.com/MasaCMS/MasaCMS/assets/115802974/2998d7e1-4ac7-436b-9a89-7ab64b2a4151)
Outputs as
![Screenshot 2024-03-08 at 01 30 50](https://github.com/MasaCMS/MasaCMS/assets/115802974/359f20c4-91e3-47ee-acb2-ab3de1c565ac)

**Desktop (please complete the following information):**
 - OS: macOS 12.6.7
 - Browser chrome 122.0.6261.112
 - Version 7.4.6

**Environment (please complete the following information):**
 - OS: CommandBox
 - CFML Engine Lucee 5.4.3.2
 - Database MySQL

**Additional context**
The issue appears to be from the change (commit fb27f8) in /core/mura/content/contentRenderer.cfc that now uses cleanText from the structure returned by the `filterWords` function in /core/mura/Portcullis.cfc

**Comment by jeroenweareorangeeu** [comment]
Will be fixed in Masa 7.4.7. release.

**Comment by michael-hldl** [comment]
Thanks Jeroen
