### ISSUE TITLE
Image Detail cropping missing # 

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#294]
**Describe the bug**
I went to edit an image I uploaded to recrop it and got this error.

\www\admin\core\views\carch\imagedetails.cfm;missing terminating [#] for expression

Column: 281
ID: ??
Line: 126
Raw Trace:
Template: E:\Websites\dev.mysite.com\www\admin\core\views\carch\imagedetails.cfm
Type: cfml

**To Reproduce**
1. Any image that is dedicated to a page 
2. Click on the icon to crop the image
3. It throws this error

**Expected behavior**
I expected to see the various images and have the ability to re-crop them. 

**Screenshots**
![2024-03-13_13-31-34](https://github.com/MasaCMS/MasaCMS/assets/1850313/4cc15022-bc33-4c4a-8828-61fad38a4af3)

**Environment (please complete the following information):**
 - OS: [e.g. Windows Server, ]
 - CFML Engine [Lucee 5.4]
 - Database [MSSQL]
 - MASA 7.1.6

**Comment by tbugler70** [comment]
Will we see a fix for this soon. Still seeing the same issue:

Core version: 7.4.6
App Server Lucee: 5.1.0.34 
DB Server MySQL: 5.7.10
Java Version: 1.8.0_112

Also tested on Lucee: 6.0.1.83 with same result.

**Comment by OriCat101** [comment]
Is anyone working on this? Don't wanna do work that someone already did

**Comment by jeroenweareorangeeu** [comment]
Will be fixed in Masa 7.4.7. release.
