### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#304]
**Is your feature request related to a problem? Please describe.**
We have a client that also serves Europe and other countries and we are needing to put into place a CSP policy in our web.config file.  I have managed to get most of it working but I am running into issues when MASA injects scripts for the Cookie Consent and the usual scripts that is injected in the header. (function(root,config){root.queuedMuraCmds=[],root.queuedMuraPreInitCmds=[],root.deferMuraInit=function(){void 0!==root.Mura&&"function"==typeof root.Mura.init?root.Mura.init(config):("function"!=typeof root.Mura&&(root.mura=root.m=root.Mura=function(o){root.queuedMuraCmds.push(o)},root.Mura.preInit=function(o){root.queuedMuraPreInitCmds.push(o)}),setTimeout(root.deferMuraInit))},root.deferMuraInit();}
)(this,{
loginURL:"?display=login",    ECT.  

**Describe the solution you'd like**
To allow injected scripts like this, we either need to use a nonce or hash or something else, but I am not sure.  This is all kind of new to me. I really don't want to add unsafe-inline, as that just sort of defeats the purpose of having a Security policy to begin with.  I have managed to fix all the other elements except for the MASA scripts. 

**Describe alternatives you've considered**
Unsafe-Inline, but again, it defeats the purpose. 

Having a Content Security Policy is becoming increasingly important, and Google and other browsers and search engines are starting to notice it. I think MASA should consider helping us developers work on it. 

I would be happy to work on anything you guys come up with and test various options. I have gone down a deeeep rabbit hole on this one and could really use some guidance. 
Thank you
Barbara.

**Comment by jeroenweareorangeeu** [comment]
Hello Tigerlady,

Thank you for your ticket. I have taken a look at this and I think we've come a cross this before. It would be quite some effort on our part to go through the entire Masa CMS application and fix this. On the other hand, it will become more important as you already stated. I've put this up for discussion with the team in the next following weeks, if and when we can address this.
I will take in consideration your offer for testing this fix. Thank you.

With kind regards,

Jeroen
