### ISSUE TITLE
Having Issues Starting MASA CMS

### ISSUE THREAD

**Issue by Faabbas2** [MasaCMS/MasaCMS#306]
### Discussed in https://github.com/MasaCMS/MasaCMS/discussions/305

<div type='discussions-op-text'>

<sup>Originally posted by **Faabbas2** April 16, 2024</sup>
Hello I am a Junior level developer. I am trying to install MASA CMS and followed the instructions on the documentation and guidelines. I was able to have it run through the docker container and Commandbox CLI and trouble shoot any errors. It successfully creates a localhost:80 site but when I try to access the Admin Site It does not show the admin page. it instead shows the default page.
Can anyone please help me?
 I was receiving this error but I fixed via changing the driver name in the docker.yml file. I also have Coldfusion installed.

![image](https://github.com/MasaCMS/MasaCMS/assets/167245582/d4239bf6-78c8-42cf-986e-918899bbf4b6)
![image](https://github.com/MasaCMS/MasaCMS/assets/167245582/3f9d14ad-2963-43fc-bce1-1c9cc1d3405f)
![image](https://github.com/MasaCMS/MasaCMS/assets/167245582/d5f99a02-542c-4e32-965b-185aa7856875)
![image](https://github.com/MasaCMS/MasaCMS/assets/167245582/c26381c9-8233-4f63-b9f1-d0d173e2076d)

</div>

**Comment by jeroenweareorangeeu** [comment]
Hello,

The Masa CMS Admin is located under '/admin'.
In this case  http://localhost:8080/admin
