### ISSUE TITLE
How to create an alias using the MASA CMS

### ISSUE THREAD

**Issue by modemodom** [MasaCMS/MasaCMS#314]
Hello. I am unable to find where I can create an alias in the CMS.

Suppose there is a page called https://mydomain.com/support-documentation/page1.

Is there a way in the CMS to create an alias called https://mydomain.com/page1 that redirects to this page?

Thanks,
Chris

**Comment by no3rdw** [comment]
This can be done simply by creating a link object that points to the other page.  

Create a new Link object directly under the site root called 'Page1' and in the URL field enter the full or relative path to the other page '/support-documentation/page1'.

**Comment by modemodom** [comment]
Perfect. Under home was what I was missing. Thanks!!
