### ISSUE TITLE
I am forbidden (403) to view or download any file I upload to the File Browser of the MASA CMS

### ISSUE THREAD

**Issue by modemodom** [MasaCMS/MasaCMS#315]
Hi. It doesn't matter what type. I tried a zip and a jpg. Same 403 error. I wonder if it is permissions related or because I am uploading from Windows. It says...

Forbidden.
You don't have permission to access this resource.

Ideas?

Thanks,
Chris

**Comment by modemodom** [comment]
Hi All. Can anyone help?  There hasn't been a response for 5 days. Thanks!

**Comment by tsucaet** [comment]
We had the same issue when we upgraded our stack to Lucee 5.4.6.9 and Tomcat 9.0.86, we're running Masa/Lucee on a RedHat Linux. We solved this by adding "export UMASK=0022" to /opt/lucee/tomcat/setenv.sh.
If this file doesn't exist you can create this file and add the umask setting.

Related info: https://stackoverflow.com/questions/48175852/tomcat9-file-permissions-change

**Comment by jeroenweareorangeeu** [comment]
Hi @modemodom,

Sorry for the long delay.
Dit the suggestion provided by @tsucaet work? Please let met know.

Greetings,

Jeroen

**Comment by jeroenweareorangeeu** [comment]
Hello @modemodom 

Is this issue still relevant or did you find a solution?
Please let me know.

This ticket will be closed after 31 October 2024 if no further comment is provided.

Greetings,

Jeroen

**Comment by jeroenweareorangeeu** [comment]
Ticket closed due to inactivity.
