### ISSUE TITLE
Masa admin login redirect in 7.4.6

### ISSUE THREAD

**Issue by horisk-simon** [MasaCMS/MasaCMS#317]
There appears to be a bug in v7.4.6 when using Masa admin and your session times out then you log back in.
To reproduce, log in to a site's admin area and stay on the content screen, delete your session/domain cookies and then refresh the page. 
When you log in again the URL your are redirected to will be similar to https://yourwebsite.com/admin/yourwebsite.com
You are successfully logged in but will have to change the URL in your browser address bar.

**Comment by jeroenweareorangeeu** [comment]
Hello,

Check out this PR that should fix this problem:

https://github.com/MasaCMS/MasaCMS/pull/318

Love to hear your feedback.

**Comment by horisk-simon** [comment]
That looks like it fixes it, thanks.

**Comment by jeroenweareorangeeu** [comment]
Will be fixed in Masa 7.4.7. release.
