### ISSUE TITLE
Need help setting up Lucee CI for MasaCMS on Lucee-testlab

### ISSUE THREAD

**Issue by zspitzer** [MasaCMS/MasaCMS#324]
I have setup MasaCMS over on Lucee testlab 

https://github.com/lucee/lucee-testlab/actions/workflows/masaCMS.yml

Goal is to be able to run CI against the latest snapshot of Lucee 5.4, 6.0, 6.1 against Java 11 and 21 to catch any regressions

I have hacked together the following config to get things going
https://github.com/lucee/lucee-testlab/tree/main/custom/masacms

I have it mostly working for 6.1, but I'm hitting the following error, I think it's not creating the tables and I'm not familiar with MasaCMS to figure it out myself!

https://github.com/lucee/lucee-testlab/actions/runs/9651163267/job/26618434740#step:7:234

```
  [java]    [script] {"Extended_Info":"","Message":"Table 'masacms.tentity' doesn't exist","Cause":{"Extended_Info":"","Message":"Table 'masacms.tentity' doesn't exist","queryError":"select * from tentity where dynamic=1","Sql":"select * from tentity where dynamic=1","Detail":"","SQLState":"42S02","additional":["SQL":"select * from tentity where dynamic=1","DatabaseName":"MySQL","DatabaseVersion":"8.0.37-0ubuntu0.22.04.3","DriverName":"MySQL Connector/J","DriverVersion":"mysql-connector-j-8.4.0 (Revision: 1c3f5c149e0bfe31c7fbeb24e2d260cd890972c4)","Datasource":"masacms"],"TagContext":[{"Raw_Trace":"org.lucee.cfml.query_cfc$cf.udfCall(/org/lucee/cfml/Query.cfc:227)","codePrintPlain":"","column":0,"line":227,"template":"/org/lucee/cfml/Query.cfc","id":"??","type":"cfml","codePrintHTML":""},{"Raw_Trace":"org.lucee.cfml.query_cfc$cf.udfCall(/org/lucee/cfml/Query.cfc:37)","codePrintPlain":"","column":0,"line":37,"template":"/org/lucee/cfml/Query.cfc","id":"??","type":"cfml","codePrintHTML":""},{"Raw_Trace":"bean.beanfactory_cfc$cf.udfCall1(/mura/bean/beanFactory.cfc:269)","codePrintPlain":"267:     function loadDynamicEntities() {
```

**Comment by jeroenweareorangeeu** [comment]
Take a look at this other issue  and solution which is the same, I think:

https://github.com/MasaCMS/MasaCMS/issues/313

**Comment by jeroenweareorangeeu** [comment]
Hi Zac,

Sorry for the long delay. Have you been succesful in fixing this issue with my comment?
Are the tests running correctly now? Please let me know.

Greetings,

Jeroen

**Comment by jeroenweareorangeeu** [comment]
Hello @zspitzer,

Is this issue still relevant or did you find a solution?
Please let me know.

This ticket will be closed after 31 October 2024 if no further comment is provided.

Greetings,

Jeroen

**Comment by jeroenweareorangeeu** [comment]
Ticket closed due to inactivity.
