### ISSUE TITLE
Ckeditor - config.js.cfm ignored

### ISSUE THREAD

**Issue by tbugler70** [MasaCMS/MasaCMS#325]
**Describe the bug**
MASA 7.4.7 - Attempting to turn off Content Filtering in ckeditor, but the config.js.cfm file in my theme is ignored.

**To Reproduce**
Update config.js.cfm in theme folder (adding config.allowedContent = true;)
Upload to server
In Masa - reload application
Go to page and paste code that was beeing re-written
Code still gets re-written

**Expected behavior**
Ckeditor does not filter my content and leaves it as pasted.

**Screenshots**
![image](https://github.com/MasaCMS/MasaCMS/assets/50739362/b35206fb-281a-44b6-8980-bb1ce3b8b8ff)

re-written to

![image](https://github.com/MasaCMS/MasaCMS/assets/50739362/51837f6a-5dab-4649-9ed5-3675f7bb86c9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 -Version 126.0.6478.127 (Official Build) (64-bit)

**Environment (please complete the following information):**
 - OS: Linux
 - CFML Engine Lucee 5.4.6.9
 - Database MariaDB 5.5.5

**Smartphone (please complete the following information):**

**Additional context**
Have also restarted Lucee, tried incognito mode as well as other browsers

**Comment by jeroenweareorangeeu** [comment]
Ticket closed due to inactivity.
