### ISSUE TITLE
Bug: Selectboxes in new page edit accordion

### ISSUE THREAD

**Issue by PeterBowater** [MasaCMS/MasaCMS#41]
Hey guys,

Spotted this while evaluating 7.3 as an upgrade for one of our sites. If you have an extended attribute that uses a selectbox, it is hidden from view:

![image](https://user-images.githubusercontent.com/807991/153881805-016c795b-a2e2-4ea9-b8f0-4e2ace7bf446.png)

The suspicious line is this one:

https://github.com/MasaCMS/MasaCMS/blob/8998517cbadf79c82e78b70fe3128e0fbec62a17/admin/assets/less/nice-select.less#L205

There could be something else going on of course, i.e. JS picking on something it isn't supposed to :) 

TVM,

Peter.

**Comment by guustnieuwenhuis** [comment]
Thanks for raising this issue @PeterBowater, we're aiming to fix this in the next patch release.

**Comment by guustnieuwenhuis** [comment]
resolved in version 7.3.1
