### ISSUE TITLE
Bug: Extended attribute type="file" broken in new accordion

### ISSUE THREAD

**Issue by PeterBowater** [MasaCMS/MasaCMS#43]
Guys,

Spotted this while checking out 7.3:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/807991/153887639-dd083965-5b93-4b93-ae1f-e237d16e9142.png">

This is a type="file" extended attribute specified in the config.xml.cfm, as you can see, the field title is occluded buy the following background, and the buttons appears to be out of position. Also missing 'via URL', 'select existing' options.

Thanks very much :)

Peter.

**Comment by guustnieuwenhuis** [comment]
Thanks for raising this issue @PeterBowater, we're aiming to fix this in the next patch release.
