### ISSUE TITLE
Bug: /admin/temp retained as relative path when switching from deploy bundle to file manager

### ISSUE THREAD

**Issue by PeterBowater** [MasaCMS/MasaCMS#44]
Hi Guys (again, sorry....),

Playing with 7.3 again, I deployed a bundle (which worked great!), from the /admin/temp folder as it has been for a very long time .

Afterwards I went to check out the new file manager, unfortunately the spinner got stuck and it was unable to list the files, looking a bit more it appears to be trying to list files from users files/admin/temp, which doesn't exists, and then it fails:

![image](https://user-images.githubusercontent.com/807991/153892110-09ae2eff-b3e0-415a-bc9a-874309a77aba.png)

You can see the > admin > temp in the crumbtrail at the top of the page, which shouldn't be there! I guess it is trying to persist a selected path, unfortunately not in the correct root.

Console error gives some indication of what is going on:

![image](https://user-images.githubusercontent.com/807991/153892199-b0f8ba76-58fa-4a1c-af4b-62cdc7840bc8.png)

I was able to get round it by hiding the spinner and then you can click on any of the buttons to the right and it works fine from then on :) 

Thanks,

Peter.

**Comment by guustnieuwenhuis** [comment]
Thanks for raising this issue @PeterBowater, we're aiming to fix this in the next patch release.

**Comment by guustnieuwenhuis** [comment]
resolved in version 7.3.1

**Comment by guustnieuwenhuis** [comment]
resolved in version 7.3.1
