### ISSUE TITLE
Filebrowser: Filename with allowed extension fails if filename has two full stops in it

### ISSUE THREAD

**Issue by PeterBowater** [MasaCMS/MasaCMS#45]
Hey,

Testing the file browser, looking good so far, minor glitch noticed when trying to upload screenshots from my Mac, which have the format:

Screenshot 2022-02-14 at 14.00.28.jpg

The multiple '.' means the check fails against 'FMallowedExtensions' setting, and the upload fails silently.

If I try it by renaming to:

1.jpg

works 👍 

However:

1.1.jpg

Fails 👎 

Two things :
- The upload should ideally succeed even with two full stops in the filename.
- If it does fail, there should be a user notification saying it has, and why.

Thanks very much, and sorry, I know I am bombarding you a bit today!

Peter.

**Comment by guustnieuwenhuis** [comment]
Thanks for raising this issue @PeterBowater, we're aiming to fix this in the next patch release.

**Comment by guustnieuwenhuis** [comment]
resolved in version 7.3.1
