### ISSUE TITLE
Enhancement: Associated Image

### ISSUE THREAD

**Issue by brucebailey** [MasaCMS/MasaCMS#59]
It would be nice when adding an associated image to be able to "select image" and have it look in your assets/Image but also the Cache directory so you have access to all images.

**Comment by jeroenweareorangeeu** [comment]
Hello @brucebailey,

Sorry for the long, long delay.
The cache directory is more of an internal mechanism for caching images obviously.
So it's not te be referenced directly. You just need to pick / upload the image you want to use as an associated image and then let MASA CMS figure out how to display it. Let me know if this clarifies it or you have other thoughts about this.

This ticket will be closed after 30th September 2024 if no further comment is provided.

Greetings,

Jeroen

**Comment by jeroenweareorangeeu** [comment]
Ticket closed after inactivity.
