### ISSUE TITLE
Deploy site bundle problem

### ISSUE THREAD

**Issue by Tristanimve** [MasaCMS/MasaCMS#65]
Hello, 

Just updated to Masa 7.3.1 and I can't deploy sites bundles any more.

When i select bundle on server, I can find my file, select it,  and then click on save settings. 
No error shown but nothing has been done !

config : 
App Server Lucee (5.3.8.206)
DB Server MySQL (8.0.28-0ubuntu0.20.04.3)
Java Version 11.0.11
OS Version Linux (5.4.0-91-generic) 

Thank's for support & best regards

**Comment by guustnieuwenhuis** [comment]
Hi @Tristanimve!
Could this be related to the fix by @titiscan? https://github.com/MasaCMS/MasaCMS/pull/63
Could you take his fix and apply it on your code to test it?

**Comment by titiscan** [comment]
Hi, my fix is only for export :)
After investigating, it seems that the filebrowser.js returns full url (with http://) which is added to serverpath and cause a silent error.
By correcting the path in the input file, the import works.
hope I'm clear.

**Comment by guustnieuwenhuis** [comment]
resolved in version 7.3.2
