### ISSUE TITLE
Site settings email username and password limited to 50 chars

### ISSUE THREAD

**Issue by PeterBowater** [MasaCMS/MasaCMS#66]
Hi! Me again... :) 

Doing some testing locally with form handling, attempting to use mailgun as it is quite easy to use and free.... however the username and password fields are limited to 50 chars, meaning the mailgun username/password get truncated and therefore unusable. Example username and password:

postmaster@sandbox1234567432123abcdef123456.mailgun.org

Any chance both fields could be upped to 255?

Not sure when it was added, but the 'test email settings' button is very handy for this!

Thanks :)

Peter

**Comment by guustnieuwenhuis** [comment]
resolved in version 7.3.2
