### ISSUE TITLE
Image properties dialog shouldn't add the domain name

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#75]
I do like the image upload that has been added to version 7.3. I have noticed that it adds the domain name to the URL.  This will have an issue if you want to generate a site bundle or export out a page to use on another site.  

In my example I am working on a dev site the URL https//dev.mydomain.com gets added to the image string.
https://dev.mydomain.com/sites/default/assets/Image/WebDesign/whatevermyimageis.png

It should only have "/sites/default/assets/Image/WebDesign/whatevermyimageis.png" 

I will manually remove this for now but future development will definitely need to have this addressed. 

![image](https://user-images.githubusercontent.com/1850313/162799811-744a23f4-994b-4288-a76a-3ec1ece0bc3d.png)

**Comment by guustnieuwenhuis** [comment]
issue resolved in version 7.3.3
