### ISSUE TITLE
Importing Site Bundle assigns incorrect siteID in tFiles

### ISSUE THREAD

**Issue by no3rdw** [MasaCMS/MasaCMS#92]
I just imported an existing Mura CMS site bundle to a _new_ site in Masa, assigning a new siteID when creating the site.  The new siteID was correctly assigned in tcontent, but 'default' was used in tfiles.  All associated images and uploaded files are missing from the newly created site, because the combination of fileID and correct siteID does not exist.

Collections were also given the default site name, as I can see the collections that should have been imported into the new site in the 'default' site, while the new site has no collections.

There may be more related issues, but unfortunately I need to perform a database restore to undo this action!

**Comment by no3rdw** [comment]
This action also erased all files in the sites/default/assets and sites/default/cache/ folders, which is not great.

**Comment by guustnieuwenhuis** [comment]
hi @no3rdw,
We haven't been able to reproduce it. Could you share with us a bundle that reproduces the issue?
